/*
 * generated by Xtext 2.35.0
 */
package edu.upb.lp.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import edu.upb.lp.CiMRuntimeModule;
import edu.upb.lp.CiMStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CiMIdeSetup extends CiMStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CiMRuntimeModule(), new CiMIdeModule()));
	}
	
}
