/*
 * generated by Xtext 2.35.0
 */
package edu.upb.lp;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CiMStandaloneSetup extends CiMStandaloneSetupGenerated {

	public static void doSetup() {
		new CiMStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
