/*
 * generated by Xtext 2.35.0
 */
package edu.upb.lp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CiMUiModule extends AbstractCiMUiModule {

	public CiMUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
